import math

SIGNALS = {
    "rpm": {
        "name": "RPM",
        "index": 1,
        "min": 0,
        "max": 7000,
        "converter": lambda x: math.trunc(float(x)),
        "label_value": lambda x: f'{x}',
    },
    "map": {
        "name": "MAP",
        "index": 2,
        "min": 20,
        "max": 200,
        "converter": lambda x: float(x),
        "label_value": lambda x: f'{math.trunc(x)}  kPa',
    },
    "lambda": {
        "name": "λ",
        "index": 6,
        "min": 0,
        "max": 2,
        "converter": lambda x: round(float(x) / 1000, 2),
        "label_value": lambda x: f'{x}',
    },
    "inj_util": {
        "name": "Inj. Util.",
        "index": 8,
        "min": 0,
        "max": 100,
        "converter": lambda x: math.trunc(float(x)),
        "label_value": lambda x: f'{x} %',
    },
    "ign": {
        "name": "Ign",
        "index": 10,
        "min": -45,
        "max": 45,
        "converter": lambda x: math.trunc(float(x)),
        "label_value": lambda x: f'{x} º',
    },
    "clt": {
        "name": "CLT",
        "index": 19,
        "min": -20,
        "max": 120,
        "converter": lambda x: round(float(x) - 273, 0),
        "label_value": lambda x: f'{x} ºC',
    },
    "iat": {
        "name": "IAT",
        "index": 20,
        "min": -20,
        "max": 120,
        "converter": lambda x: round(float(x) - 273, 0),
        "label_value": lambda x: f'{x} ºC',
    },
    "vss": {
        "name": "Vel",
        "index": 23,
        "min": 0,
        "max": 200,
        "converter": lambda x: math.trunc(float(x)),
        "label_value": lambda x: f'{x}',
    },
    "lambda_loop": {
        "name": "λ Loop",
        "index": 24,
        "min": 0,
        "max": 3,
        "converter": lambda x: math.trunc(float(x)),
        "label_value": lambda x: f'{x}',
    },
    "lambda_target": {
        "name": "λ Target",
        "index": 25,
        "min": 0,
        "max": 2,
        "converter": lambda x: round(float(x) / 1000, 2),
        "label_value": lambda x: f'{x}',
    },
    "fuel_trim": {
        "name": "Trim",
        "index": 26,
        "min": -20,
        "max": 20,
        "converter": lambda x: round((1000 - float(x)) / 10, 2),
        "label_value": lambda x: f'{x} %',
    },
}
